version: "3.9"
name: twenty

services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  server:
    image: twentycrm/twenty:${TAG}
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    ports:
      - "3000:3000"
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      BILLING_FREE_TRIAL_DURATION_IN_DAYS: ${BILLING_FREE_TRIAL_DURATION_IN_DAYS}
      BILLING_PLAN_REQUIRED_LINK: ${BILLING_PLAN_REQUIRED_LINK}
      BILLING_STRIPE_API_KEY: ${BILLING_STRIPE_API_KEY}
      BILLING_STRIPE_BASE_PLAN_PRODUCT_ID: ${BILLING_STRIPE_BASE_PLAN_PRODUCT_ID}
      BILLING_STRIPE_WEBHOOK_SECRET: ${BILLING_STRIPE_WEBHOOK_SECRET}
      ENABLE_DB_MIGRATIONS: "true"
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      IS_BILLING_ENABLED: ${IS_BILLING_ENABLED}
      IS_SELF_BILLING_ENABLED: ${IS_SELF_BILLING_ENABLED}
      IS_SIGN_UP_DISABLED: ${IS_SIGN_UP_DISABLED}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      PORT: 3000
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SERVER_URL: ${SERVER_URL}
      SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_TYPE: ${STORAGE_TYPE}
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:${TAG}
    command: ["yarn", "worker:prod"]
    environment:
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      BILLING_FREE_TRIAL_DURATION_IN_DAYS: ${BILLING_FREE_TRIAL_DURATION_IN_DAYS}
      BILLING_PLAN_REQUIRED_LINK: ${BILLING_PLAN_REQUIRED_LINK}
      BILLING_STRIPE_API_KEY: ${BILLING_STRIPE_API_KEY}
      BILLING_STRIPE_BASE_PLAN_PRODUCT_ID: ${BILLING_STRIPE_BASE_PLAN_PRODUCT_ID}
      BILLING_STRIPE_WEBHOOK_SECRET: ${BILLING_STRIPE_WEBHOOK_SECRET}
      ENABLE_DB_MIGRATIONS: "false" # it already runs on the server
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      IS_BILLING_ENABLED: ${IS_BILLING_ENABLED}
      IS_SELF_BILLING_ENABLED: ${IS_SELF_BILLING_ENABLED}
      IS_SIGN_UP_DISABLED: ${IS_SIGN_UP_DISABLED}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SERVER_URL: ${SERVER_URL}
      SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_TYPE: ${STORAGE_TYPE}
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  db:
    image: twentycrm/twenty-postgres:${TAG}
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U twenty -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  docker-data:
  db-data:
  server-local-data:
