export const FUNNELMINK_ICONS = {
  // objects
  crew: 'IconCar',
  equipment: 'IconBackhoe',
  job: 'IconPlant',
  material: 'IconPaperBag',
  service: 'IconHeartHandshake',
  workorder: 'IconChecklist',

  // fields
  accountOwner: 'IconUser',
  activityTargets: 'IconCheckbox',
  address: 'IconMap',
  annualRecurringRevenue: 'IconMoneybag',
  attachments: 'IconFileImport',
  avatarUrl: 'IconFileUpload',
  calendarEventParticipants: 'IconCalendar',
  createdAt: 'IconCalendar',
  crewLead: 'IconUserCircle',
  description: 'IconInfoCircle',
  domainName: 'IconGlobe',
  email: 'IconMail',
  favorite: 'IconHeart',
  idealCustomerProfile: 'IconTarget',
  jobTitle: 'IconBriefcase',
  linkedinLink: 'IconBrandLinkedin',
  messageParticipants: 'IconUserCircle',
  name: 'IconArticle',
  phone: 'IconPhone',
  position: 'IconHierarchy2',
  stage: 'IconTargetArrow',
  stickyNote: 'IconNote',
  timelineActivities: 'IconTimelineEvent',
  xLink: 'IconBrandX',
};